#!/usr/bin/env sh
. "$(dirname "$0")/husky.sh"

echo "🔎 Running lint-staged..."

npx lint-staged

if [ $? -ne 0 ]; then
  echo "❌ Lint-staged failed. Please fix errors before committing."
  exit 1
fi
