name: E2E Tests & Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    name: Run Tests & Build Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Start the server in background
        run: npm run start &

      - name: Wait for http://localhost:3000
        run: npx wait-on http://localhost:3000

      - name: Run WDIO tests
        run: npm run wdio:e2e

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

  # pages: only on real pushes to main, self‑contained publish
  pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Publish Allure to GitHub Pages
    needs: e2e
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Download Allure artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: ./allure-report
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com

