name: E2E Tests & Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    name: Run Tests & Build Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run WDIO tests
        run: npm run test:wdio

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

  pages:
    name: Publish Allure to GitHub Pages
    needs: e2e
    environment:
      name: github-pages
      url: https://Afroid.github.io/i75-recap-site/
    runs-on: ubuntu-latest

    # grant permissions to push to gh-pages
    permissions:
      contents: write
      pages: write
      id-token: write

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # branch where you want to publish the report
          publish_branch: gh-pages
          publish_dir: ./allure-report
          # commit as the GitHub Actions bot
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
