name: Label PR on Open

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'Ready for Review' label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 👀 Ready for Review 👀
